import type { ToolSeed } from "./types";

export const TOOLS: ToolSeed[] = [
  {
    id: "m365-copilot",
    name: "Microsoft 365 Copilot",
    category: "Enterprise productivity",
    description:
      "AI assistant embedded in Word, Excel, PowerPoint, Outlook, Teams and SharePoint.",
    capabilities: [
      "document_generation",
      "summarization",
      "meeting_intelligence",
      "email_drafting",
      "presentations",
      "analytics",
      "workflow_automation",
      "m365_native",
    ],
    riskRating: "low",
    licensing: "Enterprise license required (per user / month)",
    integrations: [
      "microsoft_365",
      "teams",
      "sharepoint",
      "outlook",
      "onedrive",
      "power_automate",
      "power_bi",
    ],
    costEstimate: "$30 / user / month",
    personas: ["executive", "manager", "analyst", "specialist", "administrator"],
    useCases: ["meetings", "documents", "email", "presentations", "spreadsheets", "automation"],
    complianceNotes:
      "Enterprise data boundary. Inherits M365 compliance (SOC2, ISO 27001, HIPAA, GDPR).",
  },
  {
    id: "claude-ai",
    name: "Claude.ai",
    category: "General reasoning",
    description:
      "Anthropic's flagship assistant for long-context analysis, writing and reasoning.",
    capabilities: [
      "document_generation",
      "summarization",
      "research",
      "analytics",
      "writing",
      "long_context",
      "reasoning",
    ],
    riskRating: "medium",
    licensing: "Team / Enterprise plans available",
    integrations: ["api", "web"],
    costEstimate: "$25–60 / user / month (Team / Enterprise)",
    personas: ["analyst", "consultant", "specialist", "executive"],
    useCases: ["analysis", "writing", "research", "documents", "strategy"],
    complianceNotes: "Enterprise plan offers SSO, audit logs, no training on customer data.",
  },
  {
    id: "claude-code",
    name: "Claude Code (desktop)",
    category: "Developer tooling",
    description:
      "Agentic coding assistant that operates on local repositories from the terminal / desktop.",
    capabilities: ["coding", "agentic_coding", "refactoring", "code_review", "automation", "testing"],
    riskRating: "medium",
    licensing: "Pro / Team subscription",
    integrations: ["github", "local_filesystem", "cli"],
    costEstimate: "$20–40 / user / month",
    personas: ["engineer", "developer", "technical"],
    useCases: ["coding", "refactor", "agentic_dev"],
    complianceNotes: "Runs locally; review which repos and secrets it can access.",
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    category: "General assistant",
    description: "OpenAI's general-purpose assistant for writing, brainstorming and analysis.",
    capabilities: [
      "document_generation",
      "summarization",
      "research",
      "writing",
      "image_generation",
      "analytics",
      "reasoning",
    ],
    riskRating: "medium",
    licensing: "Team / Enterprise plans available",
    integrations: ["api", "web"],
    costEstimate: "$25–60 / user / month (Team / Enterprise)",
    personas: ["beginner", "intermediate", "analyst", "specialist", "executive"],
    useCases: ["writing", "brainstorm", "summarize", "research", "image_generation"],
    complianceNotes: "Enterprise plan offers SSO, audit logs, no training on customer data.",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    category: "Developer tooling",
    description: "Inline AI pair programmer for IDEs (VS Code, JetBrains, Visual Studio).",
    capabilities: ["coding", "code_completion", "code_review", "testing", "ide_native"],
    riskRating: "low",
    licensing: "Business / Enterprise per seat",
    integrations: ["github", "vscode", "jetbrains", "visual_studio"],
    costEstimate: "$19–39 / user / month",
    personas: ["engineer", "developer", "technical"],
    useCases: ["coding", "ide_completion", "tests"],
    complianceNotes: "Business plan: no code retention, IP indemnity, SSO.",
  },
  {
    id: "claude-chatbot",
    name: "Claude (chatbot)",
    category: "Conversational assistant",
    description: "Conversational Claude experience for business users — Q&A, writing, summarization.",
    capabilities: ["summarization", "writing", "research", "customer_support", "conversational"],
    riskRating: "medium",
    licensing: "Team / Enterprise",
    integrations: ["web", "api"],
    costEstimate: "$25 / user / month (Team)",
    personas: ["beginner", "intermediate", "specialist"],
    useCases: ["q_and_a", "summarize", "customer_support"],
    complianceNotes: "Same governance as Claude.ai Enterprise.",
  },
  {
    id: "amazon-q",
    name: "Amazon Q",
    category: "AWS-aware assistant",
    description: "Assistant tuned for AWS environments and business data on AWS.",
    capabilities: ["analytics", "coding", "automation", "aws_operations", "data_science"],
    riskRating: "low",
    licensing: "Per user / month (Business or Developer)",
    integrations: ["aws", "quicksight", "s3", "redshift"],
    costEstimate: "$20–25 / user / month",
    personas: ["engineer", "analyst", "administrator", "developer"],
    useCases: ["aws_data", "aws_ops", "data_analysis", "coding"],
    complianceNotes: "Operates inside AWS account; respects IAM and data residency.",
  },
  {
    id: "gemini-enterprise",
    name: "Gemini Enterprise",
    category: "Enterprise productivity",
    description: "Google's enterprise assistant integrated with Workspace and multimodal inputs.",
    capabilities: [
      "document_generation",
      "summarization",
      "meeting_intelligence",
      "image_generation",
      "analytics",
      "multimodal",
      "google_native",
    ],
    riskRating: "low",
    licensing: "Enterprise license per user",
    integrations: ["google_workspace", "gmail", "google_meet", "google_drive"],
    costEstimate: "$30 / user / month",
    personas: ["executive", "manager", "analyst", "specialist"],
    useCases: ["meetings", "documents", "spreadsheets", "image_generation"],
    complianceNotes: "Enterprise data boundary; inherits Workspace compliance posture.",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    category: "Research",
    description: "AI search with cited sources for fast, verifiable research.",
    capabilities: ["research", "summarization", "citations", "web_search"],
    riskRating: "medium",
    licensing: "Pro / Enterprise plans",
    integrations: ["web", "api", "slack"],
    costEstimate: "$20–40 / user / month",
    personas: ["analyst", "consultant", "specialist", "researcher"],
    useCases: ["research", "market_intel", "quick_facts"],
    complianceNotes: "Enterprise plan offers SSO, no training on prompts.",
  },
];

export const TOOL_BY_ID: Record<string, ToolSeed> = Object.fromEntries(
  TOOLS.map((t) => [t.id, t]),
);